import { I18nConfigEntity } from '@core/i18n/config';

export const FiltersAsideConfig = {
  i18n: {
    petDetailsTitle: 'filtersAside.petDetailsTitle',
    dogLabel: 'filtersAside.dogLabel',
    catLabel: 'filtersAside.catLabel',
    petTypeLabel: 'filtersAside.petTypeLabel',
    petAgeLabel: 'filtersAside.petAgeLabel',
    petAgeSubtitle: 'filtersAside.petAgeSubtitle',
    petWeightLabel: 'filtersAside.petWeightLabel',
    petWeightSubtitle: 'filtersAside.petWeightSubtitle',
    noCarrierLabel: 'filtersAside.noCarrierLabel',
    yesLabel: 'filtersAside.yesLabel',
    noLabel: 'filtersAside.noLabel',
    travelDetailsTitle: 'filtersAside.travelDetailsTitle',
    routeLabel: 'filtersAside.routeLabel',
    datesLabel: 'filtersAside.datesLabel',
    departureDateLabel: 'filtersAside.departureDateLabel',
    returnDateLabel: 'filtersAside.returnDateLabel',
    passengerAndCabinClassLabel: 'filtersAside.passengerAndCabinClassLabel',
    passengerLabel: 'filtersAside.passengerLabel',
    adultsLabel: 'filtersAside.adultsLabel',
    adultsSubLabel: 'filtersAside.adultsSubLabel',
    childrenLabel: 'filtersAside.childrenLabel',
    childrenSubLabel: 'filtersAside.childrenSubLabel',
    cabinClassLabel: 'filtersAside.cabinClassLabel',
    economyClass: 'filtersAside.economyClass',
    businessClass: 'filtersAside.businessClass',
    passengerSingular: 'filtersAside.passengerSingular',
    passengerPlural: 'filtersAside.passengerPlural',
    cancelLabel: 'filtersAside.cancelLabel',
    saveLabel: 'filtersAside.saveLabel',
    certificatesLabel: 'filtersAside.certificatesLabel',
    emotionalSupport: 'filtersAside.emotionalSupport',
    serviceAnimal: 'filtersAside.serviceAnimal',
    airlinesStopsLabel: 'filtersAside.airlinesStopsLabel',
    allowStops: 'filtersAside.allowStops',
    noStops: 'filtersAside.noStops',
    baggageFareLabel: 'filtersAside.baggageFareLabel',
    airlinesLabel: 'filtersAside.airlinesLabel',
    petFriendlyAirlinesLabel: 'filtersAside.petFriendlyAirlinesLabel',
    travelTimeLabel: 'filtersAside.travelTimeLabel',
    stopoverAirportLabel: 'filtersAside.stopoverAirportLabel',
    priceLabel: 'filtersAside.priceLabel',
    stopoverTimeLabel: 'filtersAside.stopoverTimeLabel',
    updateButton: 'filtersAside.updateButton',
    filterButton: 'filtersAside.filterButton',
    breedLabel: 'filtersAside.breedLabel',
    breedPlaceholder: 'filtersAside.breedPlaceholder',
    originLabel: 'filtersAside.originLabel',
    destinationLabel: 'filtersAside.destinationLabel',
  },
} as const satisfies I18nConfigEntity;

export type ResolvedFiltersAsideTexts = {
  [K in keyof typeof FiltersAsideConfig.i18n]: string;
};
